export const aboutUs = {
  pageTitle: 'CV',
  pageAbout: 'kratak istorijat i opis poslova',
  officeOwner: 'osnivač i vlasnik advokatske kancelarije lekić',
  owner: 'advokat miloš lekić',
  text: 'Rođen je 10.12.1981. godine u Beogradu. Završio je osnovnu i srednju školu u Beogradu. 2000 godine upisuje Pravni fakultet u Beogradu a koji završava 2005 godine. i nakon završetka osnovnih studija edukaciju i usavršavanje nastavlja na Univerzitetu Berkley USA i u drugim obrazovnim institucijama u Sjedinjenim američkim državama gde je i magistrirao na trgovinskom pravu u međunarodnom poslovanju 2008 godine. Bio je najmladji advokat koji je ikada postupao-branio pred Višim sudom u Beogradu-posebno odeljenje Višeg suda okrivljene od osnivanja specijalnog suda u Beogradu 2003 godine za krivična dela iz oblasti privrednog kriminala. Advokaturom se bavi od 2009 godine te je član advokatske komore Beograda i advokatske komore Srbije.',
  text2: 'Advokat Miloš Lekić poseduje potrebne Sertifikate i Licence za odbranu maloletnih lica u postupcima u Republici Srbiji, za zastupanje oštećenih maloletnih lica a može postupati u svim krivičnim, parničnim, vanparničnim, upravnim i drugim predmetima i u svim drugim oblastima advokatskog rada u Republici Srbiji. Advokatska kancelarija Miloša Lekića danas ima još tri stalno zaposlena advokata te četiri advokatska pripravnika. Advokatska kancelarija je danas specijalizovana za pružanje usluga iz oblasti privrednog, korporativnog prava kao i prava iz oblasti ustavnih garancija fizičkih lica kao pojedinaca te njihove zaštite u ostvarivanju navedenih prava pred domaćim I međunarodnim sudovima.',
  text3: 'Takođe zastupnici smo, i zastupali pravna lica (Zastava automobili ad u stečaju, Magnohrom doo u stečaju, Jugoeksport korporacija u stečaju deoničarsko društvo, Prvi maj Pirot ad u stečaju, Elektroporcelan ad u stečaju, Pobeda Promet ad u stečaju, BD agro ad u stečaju PKB voćarske plantaže u stečaju) i drugih posebnih pravnih subjekata na teritoriji Republike Srbije (pravna lica u restruktuiranju i stečaju). Kancelarija je bila 2015-2017 godine stručni savetnik RS-Agencije za licenciranje stečajni upravnika (ALSU), RS- Agencije za bezbednost saobraćaja (ABS) 2014-2015 godine, lokalne samouprave (grad Zaječar 2013-2016 godine) gde je aktivno učestvovala na izradi i primeni podzakonskih akata kao i izrade projekata javno privatnog partnerstva (PPI) kako sa domaćim tako i međunarodnim investitorima. Kancelarija posebno ima veliko iskustvo u radu državne i lokalne samouprave na teritoriji Republike Srbije gde je aktivno učestvovala u povećanju efikasnosti i konsolidacije kako državnih tako i organa lokalne samouprave na teritoriji RS.',
  text4: 'Advokatska kancelarija Lekić danas zastupa velikih broj stranih (VICTOR GROUP GMBH; FUJITSU-SIEMENS; PACOM INTERNACIONAL; PLASTIC AD; SHANGHAI ELECTRIC; BJELJINA GAS DOO) i domaćih pravnih lica (ADP DOO; GRAFO MARKET DOO; DP NOVI SAD GAS) takođe advokatska kancelarija poseduje veliko iskustvo u oblasti bankarstva i naplate potraživanja u korist banaka i drugih pravnih lica (kancelarija zastupa/la AGROBANKU AD kao i NOVU AGROBANKU AD u postupku stečaja kao i naplate dospelih i neizmirenih obaveza kako od strane pravnih tako i od strane fizičkih lica). Advokat Miloš Lekić je bio predsednik i član Upravnog odbora privrednog društva “Društveno preduzeće Novi Sad GAS” 2018-2019 godine (najveći distributer prirodnog gasa krajnjim korisnicima na teritoriji RS). Advokatska kancelarija se bavi i ima iskustva sa naplatom komunalnih usluga (naplata dugova od potrošača kako komercijalnih tako i fizičkih lica). Takođe advokatska kancelarija je vršila i aktivno učestvovala u eksproprijaciji zemljišta (javni interes-gasifikacija) na teritoriji Bosne i Hercegovine, Republika Srpska i učestvovala u postupcima pred “Komisijom za koncesije Republike Srpske”.',
  text5: 'Posebno napominjemo veliko iskustvo u postupcima pred “Konkurencijskim savjetom” Bosne I Hercegovine i to u postupcima koje je to telo kao nezavisni organ pokretalo protiv pravnih subjekata zbog sprečavanja, ograničavanja ili narušavanja tržišne konkurencije na teritoriji Bosne i Hercegovine kao i izvan teritorije BIH a koje su imale uticaja na teritoriju iste. Kancelarija je učestvovala i u zaključivanju sporazuma (pravna regulativa) između pravnih lica-privrednih subjekata a koji kao takvi mogli biti ili su bili predmet ispitivanja od strane “Konkurencijskog savjeta” Bosne i Hercegovine. Posebno posedujemo dugogodišnje iskustvo u zastupanju i zaštiti ljudskih i manjinskih prava pred Ustavnim sudom RS i međunarodnim sudom pravde u Strazburu. Pružamo pravnu zaštitu i saradnju licima sa posebnim potrebama (pro bono) kao i zaštitu prava maloletnika i žena u sudskim i upravnim postupcima te krivičnim postupcima kao punomoćnici oštećenih za krivična dela iz oblasti nasilja u porodici. Do sada smo učestvovali i pravno pomagali u osnivanju i praćenju rada organizacija iz nevladinog sektora i udruženjima a koja se bave zaštitom od nasilja u porodici kao i organizacijama koja se bave izjednačavanjem položaja oba pola a u skladu sa Ustavom RS i drugim pozitivno-pravnim propisima koji prate navedenu materiju.',
};
