import t from 'translate';

export const AREAS = [
  {
    id: 1,
    title: /* t('areas.law') */ 'Krivično pravo',
    text: 'Za odbranu je svakako od značaja i novina koja se ogleda u prikupljanju dokaza i predlaganju istih. Prema aktuelnom zakonodavstvu, odbrana kao i okrivljeni kao stranke u postupku imaju prava da predlažu dokaze koje idu u korist okrivljenom, ali sve dokaze na kojima se zasniva odbrana okrivljenog su dužni da predlože najkasnije na pripremnom ročištu ili na prvom glavnom pretresu ukoliko pripremno ročište nije održano, uz upozorenje suda da se neće izvoditi oni dokazi koji su bili poznati, a nisu predloženi u ovom periodu. U ovakvoj situaciji je od velikog značaja da efikasnost branioca bude na visini zadatka kako se ne bi ugrozila odbrana okrivljenog koja bi imala za posledicu nepovoljniji položaj samog okrivljenog u toku trajanja krivičnog postupka.',
    text2: 'Aktuelni Zakonik o krivičnom postupku predviđa još brojne novine kojima se daje značajna uloga braniocima u toku trajanja istrage kao i u toku trajanja krivičnih postupaka. Ono što je sigurno je to da najvažniji interes svakog branioca treba da bude pružanje najdelotvornije odbrane okrivljenom pred organima postupka uz potpuno raspolaganje stručnog znanja i veština.',
    areaAbout: 'Rođen je 10.12.1981. godine u Beogradu. Završio je osnovnu i srednju školu u Beogradu. 2000 godine upisuje Pravni fakultet u Beogradu a koji završava 2005 godine. i nakon završetka osnovnih studija edukaciju i usavršavanje nastavlja na Univerzitetu Berkley USA i u drugim obrazovnim institucijama u Sjedinjenim američkim državama gde je i magistrirao na trgovinskom pravu u međunarodnom poslovanju 2008 godine. Bio je najmladji advokat koji je ikada postupao-branio pred Višim sudom u Beogradu-posebno odeljenje Višeg suda okrivljene od osnivanja specijalnog suda u Beogradu 2003 godine za krivična dela iz oblasti privrednog kriminala. Advokaturom se bavi od 2009 godine te je član advokatske komore Beograda i advokatske komore Srbije Advokat Miloš Lekić poseduje ',
    work: ' potrebne Sertifikate i Licence za odbranu maloletnih lica u postupcima u Republici Srbiji, za zastupanje oštećenih maloletnih lica a može postupati u svim krivičnim, parničnim, vanparničnim, upravnim i drugim predmetima i u svim drugim oblastima advokatskog rada u Republici Srbiji, Advokatska kancelarija Miloša Lekića danas ima još tri stalno zaposlena advokata te četiri advokatska pripravnika. Advokatska kancelarija je danas specijalizovana za pružanje usluga iz oblasti privrednog, korporativnog prava kao i prava iz oblasti ustavnih garancija fizičkih lica kao pojedinaca te njihove zaštite u ostvarivanju navedenih prava pred domaćim I međunarodnim sudovima.',
    help: 'Takođe zastupnici smo, i zastupali pravna lica (Zastava automobili ad u stečaju, Magnohrom doo u stečaju, Jugoeksport korporacija u stečaju deoničarsko društvo, Prvi maj Pirot ad u stečaju, Elektroporcelan ad u stečaju, Pobeda Promet ad u stečaju, BD agro ad u stečaju PKB voćarske plantaže u stečaju) i drugih posebnih pravnih subjekata',
  },
  {
    id: 2,
    title: 'Korporativno pravo',
    text: 'Privredno pravo čini zapravo skup pravnih normi o pravnom položaju privrednih subjekata ali i njihovom pravnom poslovanju na tržištu. Konkretno se privredno pravo odnosi na pitanja regulisanja pravnog položaja preduzeća i drugih subjekata koji se pojavljuju u privredi, kao i njihovim odnosima u pravnom prometu. Usluge advokatske kancelarije obuhvataju ne samo generalno usklađivanje poslovanja privrednih subjekata sa važećim propisima, već i zastupanje u konkretnim oblastima.',
    text2: '',
    areaAbout: 'Rođen je 10.12.1981. godine u Beogradu. Završio je osnovnu i srednju školu u Beogradu. 2000 godine upisuje Pravni fakultet u Beogradu a koji završava 2005 godine. i nakon završetka osnovnih studija edukaciju i usavršavanje nastavlja na Univerzitetu Berkley USA i u drugim obrazovnim institucijama u Sjedinjenim američkim državama gde je i magistrirao na trgovinskom pravu u međunarodnom poslovanju 2008 godine. Bio je najmladji advokat koji je ikada postupao-branio pred Višim sudom u Beogradu-posebno odeljenje Višeg sudačna dela iz oblasti privrednog kriminala. Advokaturom se bavi od 2009 godine te je član advokatske komore Beograda i advokatske komore Srbije Advokat Miloš Lekić poseduje ',
    work: ' potpcima u Republici Srbiji, za zastupanje oštećenih maloletnih lica a može postupati u svim krivičnim, parničnim, vanparničnim, upravnim i drugim predmetima i u svim drugim oblastima advokatskog rada u Republici Srbiji, Advokatska kancelarija Miloša Lekića danas ima još tri stalno zaposlena advokata te četiri advokatska pripravnika. Advokatska kancelarija je danas specijalizovana za pružanje usluga iz oblasti privrednog, korporativnog prava kao i prava iz oblasti ustavnih garancija fizičkih lica kao pojedinaca te njihove zaštite u ostvarivanju navedenih prava pred domaćim I međunarodnim sudovima.',
    help: 'Tdoo u stečaju, Jugoeksport korporacija u stečaju deoničarsko društvo, Prvi maj Pirot ad u stečaju, Elektroporcelan ad u stečaju, Pobeda Promet ad u stečaju, BD agro ad u stečaju PKB voćarske plantaže u stečaju) i drugih posebnih pravnih subjekata',
  },
  {
    id: 3,
    title: 'Naknada štete',
    text: 'Pod pojmom štete podrazumeva se umanjenje nečije imovine (obična šteta) i sprečavanje njenog povećanja (izmakla korist), kao i nanošenje fizičkog ili psihičkog bola ili straha drugome (nematerijalna šteta). Angažovanjem advokata koji će zastupati vaše interese postižete da se bez direktnog angažovanja obeštetite odnosno dobijete adekvatnu novčanu nadoknadu u slučajevima kada je jedno lice (štetnik) izvršilo neki vid povrede prava drugog lica (oštećenog) u vidu prouzrokovanja bilo materijalne ili ne materijalne štete.',
    text2: 'Advokatska kancelarija se bavi i ima iskustva sa naplatom komunalnih usluga (naplata dugova od potrošača kako komercijalnih tako i fizičkih lica). Takođe advokatska kancelarija je vršila i aktivno učestvovala u eksproprijaciji zemljišta (javni interes- gasifikacija) na teritoriji Bosne i Hercegovine, Republika Srpska i učestvovala u postupcima pred “Komisijom za koncesije Republike Srpske”.',
    areaAbout: 'Rođen je 10.12.1981. godine u Beogradu. Završio je osnovnu i srednju školu u Beogradu. 2000 godine upisuje Pravni fakultet u Beogradu a koji završava 2005 godine. i nakon završetka osnovnih studija edukaciju i usavršavanje nastavlja na Univerzitetu Berkley USA i u drugim obrazovnim institucijama u Sjedinjenim američkim državama gde je i magistrirao na trgovinskom pravu u međunarodnom poslovanju 2008 godine. Bio je najmladji advokat koji je ikada postupao-branio pred Višim sudom u Beogradu-posebno odeljenje Višeg suda okrivljene od osnivanja specijalnog suda u Beogradu 2003 godine za krivična dela iz oblasti privrednog kriminala. Advokaturom se bavi od 2009 godine te je član advokatske komore Beograda i advokatske komore Srbije Advokat Miloš Lekić poseduje ',
    work: ' potrebne Sertifikate i Licence za odbranu maloletnih lica u postupcima u Republici Srbiji, za zastupanje oštećenih maloletnih lica a može postupati u svim krivičnim, parničnim, vanparničnim, upravnim i drugim predmetima i u svim drugim oblastima advokatskog rada u Republici Srbiji, Advokatska kancelarija Miloša Lekića danas ima još tri stalno zaposlena advokata te četiri advokatska pripravnika. Advokatska kancelarija je danas specijalizovana za pružanje usluga iz oblasti privrednog, korporativnog prava kao i prava iz oblasti ustavnih garancija fizičkih lica kao pojedinaca te njihove zaštite u ostvarivanju navedenih prava pred domaćim I međunarodnim sudovima.',
    help: 'Takođe zastupnici smo, i zastupali pravna lica (Zastava automobili ad u stečaju, Magnohrom doo u stečaju, Jugoeksport korporacija u stečaju deoničarsko društvo, Prvi maj Pirot ad u stečaju, Elektroporcelan ad u stečaju, Pobeda Promet ad u stečaju, BD agro ad u stečaju PKB voćarske plantaže u stečaju) i drugih posebnih pravnih subjekata',
  },
  {
    id: 4,
    title: 'Opšta parnica',
    text: 'Danas građansko pravo predstavlja najpre porodicu odnosno familiju više grana prava a koje čine: opšti deo građanskog prava, stvarno pravo, porodično pravo i obligaciono pravo pa je samim tim građansko pravo zasnovano na različitim načelima. Kao specijalizovana advokatska kancelarija za građansko pravo naš zadatak je najpre da upoznamo svoje klijente sa njihovim zakonskim pravima i obavezama u okviru parničnog postupka koji je pokrenut protiv njih ili postupka koje su pokrenuli protiv drugih lica.',
    text2: 'Nakon što se u potpunosti upoznamo sa predmetom, uz primenu zakonskih regulativa koji važe za konkretan predmet odnosno slučaj, klijentu predočavamo i predlažemo moguće načine za postupanje te u skladu sa tim preduzimamo sve neophodne pravne mere.',
    areaAbout: 'Rođen je 10.12.1981. godine u Beogradu. Završio je osnovnu i srednju školu u Beogradu. 2000 godine upisuje Pravni fakultet u Beogradu a koji završava 2005 godine. i nakon završetka osnovnih studija edukaciju i usavršavanje nastavlja na Univerzitetu Berkley USA i u drugim obrazovnim institucijama u Sjedinjenim američkim državama gde je i magistrirao na trgovinskom pravu u međunarodnom poslovanju 2008 godine. Bio je najmladji advokat koji je ikada postupao-branio pred Višim sudom u Beogradu-posebno odeljenje Višeg suda okrivljene od osnivanja specijalnog suda u Beogradu 2003 godine za krivična dela iz oblasti privrednog kriminala. Advokaturom se bavi od 2009 godine te je član advokatske komore Beograda i advokatske komore Srbije Advokat Miloš Lekić poseduje ',
    work: ' potrebne Sertifikate i Licence za odbranu maloletnih lica u postupcima u Republici Srbiji, za zastupanje oštećenih maloletnih lica a može postupati u svim krivičnim, parničnim, vanparničnim, upravnim i drugim predmetima i u svim drugim oblastima advokatskog rada u Republici Srbiji, Advokatska kancelarija Miloša Lekića danas ima još tri stalno zaposlena advokata te četiri advokatska pripravnika. Advokatska kancelarija je danas specijalizovana za pružanje usluga iz oblasti privrednog, korporativnog prava kao i prava iz oblasti ustavnih garancija fizičkih lica kao pojedinaca te njihove zaštite u ostvarivanju navedenih prava pred domaćim I međunarodnim sudovima.',
    help: 'Takođe zastupnici smo, i zastupali pravna lica (Zastava automobili ad u stečaju, Magnohrom doo u stečaju, Jugoeksport korporacija u stečaju deoničarsko društvo, Prvi maj Pirot ad u stečaju, Elektroporcelan ad u stečaju, Pobeda Promet ad u stečaju, BD agro ad u stečaju PKB voćarske plantaže u stečaju) i drugih posebnih pravnih subjekata',
  },
  {
    id: 5,
    title: 'Porodično pravo',
    text: 'Porodičnim pravom se uređuju najpre brak i bračni odnosi, zatim odnosi u vanbračnoj zajednici, odnosi deteta i roditelja, usvajanje, hraniteljstvo i starateljstvo, izdržavanje, imovinski odnosi u porodici, zaštita od nasilja u porodici, postupci u vezi sa porodičnim odnosima i lično ime. Ukoliko niste u mogućnosti da se samostalno dogovorite sa svojim supružnikom ili vanbračnim partnerom oko svih aspekata vezanih za razvod braka ili pak oko podele starateljstva nad detetom, tu smo da vam pomognemo u cilju postizanja mirnog rešenja.',
    text2: '',
    areaAbout: 'Rođen je 10.12.1981. godine u Beogradu. Završio je osnovnu i srednju školu u Beogradu. 2000 godine upisuje Pravni fakultet u Beogradu a koji završava 2005 godine. i nakon završetka osnovnih studija edukaciju i usavršavanje nastavlja na Univerzitetu Berkley USA i u drugim obrazovnim institucijama u Sjedinjenim američkim državama gde je i magistrirao na trgovinskom pravu u međunarodnom poslovanju 2008 godine. Bio je najmladji advokat koji je ikada postupao-branio pred Višim sudom u Beogradu-posebno odeljenje Višeg suda okrivljene od osnivanja specijalnog suda u Beogradu 2003 godine za krivična dela iz oblasti privrednog kriminala. Advokaturom se bavi od 2009 godine te je član advokatske komore Beograda i advokatske komore Srbije Advokat Miloš Lekić poseduje ',
    work: ' potrebne Sertifikate i Licence za odbranu maloletnih lica u postupcima u Republici Srbiji, za zastupanje oštećenih maloletnih lica a može postupati u svim krivičnim, parničnim, vanparničnim, upravnim i drugim predmetima i u svim drugim oblastima advokatskog rada u Republici Srbiji, Advokatska kancelarija Miloša Lekića danas ima još tri stalno zaposlena advokata te četiri advokatska pripravnika. Advokatska kancelarija je danas specijalizovana za pružanje usluga iz oblasti privrednog, korporativnog prava kao i prava iz oblasti ustavnih garancija fizičkih lica kao pojedinaca te njihove zaštite u ostvarivanju navedenih prava pred domaćim I međunarodnim sudovima.',
    help: 'Takođe zastupnici smo, i zastupali pravna lica (Zastava automobili ad u stečaju, Magnohrom doo u stečaju, Jugoeksport korporacija u stečaju deoničarsko društvo, Prvi maj Pirot ad u stečaju, Elektroporcelan ad u stečaju, Pobeda Promet ad u stečaju, BD agro ad u stečaju PKB voćarske plantaže u stečaju) i drugih posebnih pravnih subjekata',
  },
  {
    id: 6,
    title: 'Ljudska prava',
    text: 'Pored navedenog, naša advokatska kancelarija pruža i usluge sačinjavanja kupoprodajnih ugovora u prometu nekretnina i detaljne provere prodavca, njihovog poslovanja i postojanja eventualnih rizika i ugroženosti naših klijenata u svojstvu kupaca. Provere koje vršimo daju izuzetno visok nivo pravne sigurnosti prilikom kupovine nepokretnosti, a tiču se provere kako prodavca, tako i nepokretnosti u svim nadležnim sudovima i državnim organima.',
    text2: ' Ta provera se sastoji od provere postojanja predstojećih ili postojećih izvršnih postupaka koji se vode protiv prodavca, te i provera kod Agencije za privredne registre i Narodne banke Srbije, a potom provere postojanja tereta i drugih pravni smetnji za prometovanje ili kasnije knjiženje prometovane nepokretnosti.',
    areaAbout: 'Rođen je 10.12.1981. godine u Beogradu. Završio je osnovnu i srednju školu u Beogradu. 2000 godine upisuje Pravni fakultet u Beogradu a koji završava 2005 godine. i nakon završetka osnovnih studija edukaciju i usavršavanje nastavlja na Univerzitetu Berkley USA i u drugim obrazovnim institucijama u Sjedinjenim američkim državama gde je i magistrirao na trgovinskom pravu u međunarodnom poslovanju 2008 godine. Bio je najmladji advokat koji je ikada postupao-branio pred Višim sudom u Beogradu-posebno odeljenje Višeg suda okrivljene od osnivanja specijalnog suda u Beogradu 2003 godine za krivična dela iz oblasti privrednog kriminala. Advokaturom se bavi od 2009 godine te je član advokatske komore Beograda i advokatske komore Srbije Advokat Miloš Lekić poseduje ',
    work: ' potrebne Sertifikate i Licence za odbranu maloletnih lica u postupcima u Republici Srbiji, za zastupanje oštećenih maloletnih lica a može postupati u svim krivičnim, parničnim, vanparničnim, upravnim i drugim predmetima i u svim drugim oblastima advokatskog rada u Republici Srbiji, Advokatska kancelarija Miloša Lekića danas ima još tri stalno zaposlena advokata te četiri advokatska pripravnika. Advokatska kancelarija je danas specijalizovana za pružanje usluga iz oblasti privrednog, korporativnog prava kao i prava iz oblasti ustavnih garancija fizičkih lica kao pojedinaca te njihove zaštite u ostvarivanju navedenih prava pred domaćim I međunarodnim sudovima.',
    help: 'Takođe zastupnici smo, i zastupali pravna lica (Zastava automobili ad u stečaju, Magnohrom doo u stečaju, Jugoeksport korporacija u stečaju deoničarsko društvo, Prvi maj Pirot ad u stečaju, Elektroporcelan ad u stečaju, Pobeda Promet ad u stečaju, BD agro ad u stečaju PKB voćarske plantaže u stečaju) i drugih posebnih pravnih subjekata',
  },
];

export const OPTIONS = {
  options: [
    { value: 1, label: 'Krivično pravo' },
    { value: 2, label: 'Korporativno pravo' },
    { value: 3, label: 'Naknada štete' },
    { value: 4, label: 'Opšta parnica' },
    { value: 5, label: 'Porodično pravo' },
    { value: 6, label: 'Ljudska prava' },
  ],
};
