export const SEND_CONTACT_US_REQUEST = 'SEND_CONTACT_US_REQUEST';
export const SEND_CONTACT_US_SUCCESS = 'SEND_CONTACT_US_SUCCESS';
export const SEND_CONTACT_US_FAILURE = 'SEND_CONTACT_US_FAILURE';
export const RESET_CONTACT_US_FORM = 'RESET_CONTACT_US_FORM';

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
